FROM ${basePythonContainerImage}

ARG WORKDIR=/template
RUN mkdir -p $WORKDIR
${filesToCopy}
WORKDIR $WORKDIR

ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt
ENV FLEX_TEMPLATE_PYTHON_PY_FILE=main.py

RUN if ! [ -f requirements.txt ] ; then >&2 echo "error: no requirements.txt file found" && exit 1 ; fi

# Set up custom PyPi repository
<#if saSecretName?? && airlockPythonRepo??>
RUN mkdir -p $HOME/.pip
RUN mkdir -p $HOME/.config/pip
RUN printf "[distutils]\nindex-servers =\n    ${airlockPythonRepo}\n\n[${airlockPythonRepo}]\n" > $HOME/.pip/.pypirc
RUN printf "repository: https://us-python.pkg.dev/artifact-foundry-prod/${airlockPythonRepo}/\n" >> $HOME/.pip/.pypirc
RUN printf "username: _json_key_base64\n" >> $HOME/.pip/.pypirc
RUN printf "password: $(gcloud secrets versions access latest --secret=${saSecretName} | base64 -w 0)" >> $HOME/.pip/.pypirc
RUN printf "[global]\nindex-url = https://_json_key_base64:$(gcloud secrets versions access latest --secret=${saSecretName} | base64 -w 0)@us-python.pkg.dev/artifact-foundry-prod/${airlockPythonRepo}/simple/" > $HOME/.config/pip/pip.conf
</#if>

RUN pip install keyrings.google-artifactregistry-auth -i https://pypi.org/simple/
RUN pip install -U -r --require-hashes $FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE
RUN pip download --require-hashes --no-cache-dir --dest /tmp/dataflow-requirements-cache -r $FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE

ENTRYPOINT ${entryPoint}